### ISSUE TITLE
[ci] MSRV Check (Rust 1.83) failing on main since caroml stack landed (#904–#914)

### ISSUE THREAD

**Issue by wildcard** [wildcard/caro#1049]
## Summary

The `MSRV Check (Rust 1.83)` job (`.github/workflows/ci.yml:380`) is failing on `main` and on every PR opened against `main` since the caroml stack landed (#904 through #914, merged 2026-04-29 → 2026-04-30). Build aborts with **exit code 101** (Rust compile error).

## Repro

```bash
git checkout main
rustup install 1.83
cargo +1.83 build --release --locked --no-default-features --features embedded-cpu
```

## Evidence

- Latest failing run on PR #1030 (which touches **zero** Rust files): https://github.com/wildcard/caro/actions/runs/25157188274/job/73741946132
- Branch base for PR #1030 was `208150a` (2026-04-29) — before caroml landed; failure appears in the PR's merge commit because main now contains caroml code.
- 13 caroml commits landed on main in <24h (#904–#914) introducing the new `apps/devrel/`, caroml-related Rust modules, and runtime dependencies.

## Likely cause + fix paths

One of:

1. **A new caroml crate dep requires Rust ≥1.84/2024-edition transitively.** Run `cargo +1.83 build --release --no-default-features --features embedded-cpu 2>&1 | head -50` on `main` and look for `requires Rust 2024 edition` or `unstable feature` errors.
2. **A new caroml source file uses Rust 1.84+ syntax** (`let-else` enhancements, `c""` cstr literals, etc.). Same diagnostic command will surface it.

### Suggested fixes (pick one)

- **(a)** Bump MSRV: update `Cargo.toml` `rust-version = "1.84"` (or whichever caroml requires) AND `.github/workflows/ci.yml:380` `name: MSRV Check (Rust X.YZ)` and toolchain pin (`:389`). Update README MSRV banner per `.claude/rules/release-version-alignment.md`.
- **(b)** Gate caroml behind a non-default cargo feature so the MSRV build's `--no-default-features --features embedded-cpu` excludes it. The MSRV step at `ci.yml:402` is already structured for this pattern (see comment about `knowledge` feature exclusion).

## Out of scope

This is **not** a regression introduced by PR #1030 (swarm-forge dev-flow tooling) — that PR touches no Rust files. It blocks PR #1030's merge gate cosmetically but the failure exists on main itself.

## Owner

caroml maintainer (whoever landed PRs #904–#914).

**Comment by wildcard** [comment]
@wildcard — picking this up unblocks every open PR. Filing an agent-friendly handoff so another Claude session can grab it cleanly.

## Agent handoff

**Recommended agent**: `rust-cli-expert` (or `caro-release-expert` if MSRV bump is the chosen path)

**Estimated effort**: 30–90 min (diagnosis + small fix)

### Step 1 — Diagnose (single command)

```bash
git checkout main && git pull
rustup install 1.83
cargo +1.83 build --release --locked --no-default-features --features embedded-cpu 2>&1 | tee /tmp/msrv.log | tail -80
```

The relevant error line will be one of:
- `error: package \`X\` cannot be built because it requires rustc 1.YZ`
- `error[E0658]: <feature> is only available in Rust 2024 edition`
- `error: 2024 edition is not supported`

### Step 2 — Pick fix path

| Path | When | Files to touch | Per `.claude/rules/release-version-alignment.md` |
|---|---|---|---|
| **(a) Bump MSRV** | If multiple caroml deps or files force ≥1.84 — simpler | `Cargo.toml` `rust-version`, `.github/workflows/ci.yml:380,389`, `README.md` MSRV banner, `ROADMAP.md` | Yes — invokes the 6-file release checklist if version-bumping crate too |
| **(b) Feature-gate caroml** | If 1.83 still works with `--no-default-features --features embedded-cpu` and caroml is the only blocker | `Cargo.toml` `[features]`, mark caroml mod conditional via `#[cfg(feature = "caroml")]`, `ci.yml:402` already structured for this | No — pure code change |

### Step 3 — Verify

- `cargo +1.83 build --release --locked --no-default-features --features embedded-cpu` → clean
- Push branch → MSRV Check job green
- Close this issue

### Constitution touchpoints

- `.claude/rules/git-workflow.md` — feature branch mandatory
- `.claude/rules/release-version-alignment.md` — if (a), update all 6 files
- `.claude/rules/good-boy-scout.md` — don't gold-plate; fix the MSRV failure, ship

Related: #1050, #1051 (both filed alongside #1030).

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by wildcard** [comment]
Resolved on `main` via PR #1056 (commit `72abbc5`), which bumped `rust-version` from `1.83` → `1.85`. Confirmed: `git show origin/main:Cargo.toml | grep rust-version` → `rust-version = "1.85"`, and the CI job is now `MSRV Check (Rust 1.85)`.

A parallel PR #1073 was opened from this session that attempted the same fix but proved redundant after #1056 landed first — that PR was closed without merging.

Closing as complete.

---
_Generated by [Claude Code](https://claude.ai/code)_
